
/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - Quantify data and group results by specific dimensions.
    - Understand data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/



--1-- FIND TOTAL CUSTOMERS BY COUNTRY
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC



--2-- FIND TOTAL CUSTOMERS BY GENDER
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC



--3-- FIND TOTAL CUSTOMERS BY MARITAL STATUS
SELECT 
	marital_status,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY marital_status
ORDER BY marital_status



--4-- FIND TOTAL PRODUCTS BY CATEGORY
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC



--5-- FIND TOTAL PRODUCTS BY SUBCATEGORY
SELECT 
	subcategory,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY subcategory
ORDER BY COUNT(product_key) DESC



--6-- FIND TOTAL PRODUCTS BY PRODUCT LINE
SELECT 
	product_line,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY product_line
ORDER BY COUNT(product_key) DESC



--7-- FIND TOTAL PRODUCTS BY MAINTENANCE
SELECT 
	maintenance,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY maintenance
ORDER BY COUNT(product_key) DESC



--8-- FIND AVERAGE COST PER CATEGORY
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC



--9-- FIND AVERAGE COST PER PRODUCT LINE
SELECT 
	product_line,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY product_line
ORDER BY avg_costs DESC



 --10-- FIND TOTAL REVENUE GENERATED BY EACH PRODUCT
SELECT 
	sa.product_key,
	pr.product_name,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_products pr
	ON sa.product_key = pr.product_key
GROUP BY sa.product_key, pr.product_name
ORDER BY total_revenue DESC



--11-- FIND TOTAL REVENUE GENERATED BY EACH CATEGORY
SELECT
	pr.category,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_products pr
	ON sa.product_key = pr.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC



--12-- FIND TOTAL REVENUE GENERATED BY EACH PRODUCT LINE
SELECT
	pr.product_line,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_products pr
	ON sa.product_key = pr.product_key
GROUP BY pr.product_line
ORDER BY total_revenue DESC



--13-- FIND TOTAL REVENUE GENERATED BY PRODUCT MAINTENANCE STATUS
SELECT 
	pr.maintenance,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_products pr
	ON sa.product_key = pr.product_key
GROUP BY pr.maintenance
ORDER BY total_revenue DESC



--14-- FIND TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT 
	cu.customer_key,
	cu.first_name,
	cu.last_name,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_customers cu
	ON sa.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.first_name, cu.last_name
ORDER BY total_revenue DESC



--15-- FIND TOTAL REVENUE GENERATED BY EACH COUNTRY
SELECT 
	cu.country,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_customers cu
	ON sa.customer_key = cu.customer_key
GROUP BY cu.country
ORDER BY total_revenue DESC



--16-- FIND TOTAL REVENUE GENERATED BY EACH MARITAL STATUS
SELECT 
	cu.marital_status,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_customers cu
	ON sa.customer_key = cu.customer_key
GROUP BY cu.marital_status
ORDER BY total_revenue DESC



--17-- FIND TOTAL REVENUE GENERATED BY EACH GENDER
SELECT 
	cu.gender,
	SUM(sa.sales_amount) AS total_revenue
FROM gold.fact_sales sa
LEFT JOIN gold.dim_customers cu
	ON sa.customer_key = cu.customer_key
GROUP BY cu.gender
ORDER BY total_revenue DESC

